package org.ual.hmis.LosMilagritos;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ListaAdminCasoCorrectoTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;
	@Before
	public void setUp() { 
		int browser= 0; 
		Boolean headless = false;

		switch (browser) {
		case 0: 
			System.setProperty("webdriver.gecko.driver",  "drivers/geckodriver.exe");
			FirefoxOptions firefoxOptions = new FirefoxOptions();
//			if (headless) firefoxOptions.addArguments("--headless"); // .setHeadless(headless);
			firefoxOptions.setHeadless(true); 
			driver = new FirefoxDriver(firefoxOptions);
			break;

		case 1: 
			System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
			ChromeOptions chromeOptions = new ChromeOptions();
//			if (headless) chromeOptions.addArguments("--headless"); // .setHeadless(headless);
			chromeOptions.setHeadless(true);
			driver = new ChromeDriver(chromeOptions);
			break;

		default:
			fail("Please select a browser");
			break;
		}

		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}
	@After
	public void tearDown() {
		driver.quit();
	}
	@Test
	public void listaAdminCasoCorrecto() {
		driver.get("https://my-app-1717583869591.azurewebsites.net/");

		WebDriverWait wait = new WebDriverWait(driver, 10);

		//Entrar como usuario a la app
		WebElement usernameField = wait.until(ExpectedConditions.presenceOfElementLocated(By.id("input-vaadin-text-field-6")));
		usernameField.sendKeys("user");

		WebElement passwordField = wait.until(ExpectedConditions.presenceOfElementLocated(By.id("input-vaadin-password-field-7")));
		passwordField.sendKeys("user");

		WebElement loginButton = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("vaadin-button:nth-child(2)")));
		loginButton.click();

		WebElement grid = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("vaadin-grid")));

		// Desplazar la vista al grid para asegurarse de que esté visible
		js.executeScript("arguments[0].scrollIntoView(true);", grid);

		Actions builder = new Actions(driver);

		// Realiza el mouse down
		builder.moveToElement(grid).clickAndHold().perform();
		// Realiza el mouse move
		builder.moveToElement(grid).perform();
		// Realiza el mouse up
		builder.moveToElement(grid).release().perform();

		// Espera y realiza clic en los elementos dentro del grid
		clickElement(wait, "vaadin-grid-cell-content:nth-child(114)");
		clickElement(wait, "vaadin-grid-cell-content:nth-child(186)");
		clickElement(wait, "vaadin-grid-cell-content:nth-child(146)");
		clickElement(wait, "vaadin-grid-cell-content:nth-child(187)");
		clickElement(wait, "vaadin-grid-cell-content:nth-child(155)");

		// Realiza las acciones finales en el grid
		builder.moveToElement(grid).clickAndHold().perform();
		builder.moveToElement(grid).perform();
		builder.moveToElement(grid).release().perform();

		// Clic final en el grid
		clickElement(wait, "vaadin-grid-cell-content:nth-child(107)");
	}

	private void clickElement(WebDriverWait wait, String cssSelector) {
		WebElement element = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(cssSelector)));
		// Desplazar la vista al elemento para asegurarse de que esté visible
		js.executeScript("arguments[0].scrollIntoView(true);", element);
		// Hacer clic usando JavaScript para evitar elementos superpuestos
		js.executeScript("arguments[0].click();", element);
	}
}
