package org.ual.hmis.LosMilagritos;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ModificarNumeroTelefonoCasoIncorrectoTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;
	@Before
	public void setUp() { 
		int browser= 0; 
		Boolean headless = false;

		switch (browser) {
		case 0: 
			System.setProperty("webdriver.gecko.driver",  "drivers/geckodriver.exe");
			FirefoxOptions firefoxOptions = new FirefoxOptions();
//			if (headless) firefoxOptions.addArguments("--headless"); // .setHeadless(headless);
			firefoxOptions.setHeadless(true); 
			driver = new FirefoxDriver(firefoxOptions);
			break;

		case 1: 
			System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
			ChromeOptions chromeOptions = new ChromeOptions();
//			if (headless) chromeOptions.addArguments("--headless"); // .setHeadless(headless);
			chromeOptions.setHeadless(true);
			driver = new ChromeDriver(chromeOptions);
			break;

		default:
			fail("Please select a browser");
			break;
		}

		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}
	@After
	public void tearDown() {
		driver.quit();
	}
	@Test
	public void modificarNumeroTelefonoCasoIncorrecto() {
		// Test name: Modificar Numero Telefono Caso Incorrecto
		// Step # | name | target | value
		// 1 | open | https://my-app-1717583869591.azurewebsites.net/ |
		driver.get("https://my-app-1717583869591.azurewebsites.net/");
		// 3 | wait for element | css=vaadin-grid-cell-content |
		WebDriverWait wait = new WebDriverWait(driver, 10);

		//Entrar como usuario a la app
		WebElement usernameField = wait.until(ExpectedConditions.presenceOfElementLocated(By.id("input-vaadin-text-field-6")));
		usernameField.sendKeys("user");

		WebElement passwordField = wait.until(ExpectedConditions.presenceOfElementLocated(By.id("input-vaadin-password-field-7")));
		passwordField.sendKeys("user");

		WebElement loginButton = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("vaadin-button:nth-child(2)")));
		loginButton.click();

		wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("vaadin-grid-cell-content")));
		// 4 | find elements | css=vaadin-grid-cell-content |
		List<WebElement> elements = driver.findElements(By.cssSelector("vaadin-grid-cell-content"));
		// 5 | click | css=vaadin-grid-cell-content:nth-child(74) |
		elements.get(73).click();
		// 6 | click | css=vaadin-text-field:nth-child(4) |
		driver.findElement(By.cssSelector("vaadin-text-field:nth-child(4)")).click();
		// 7 | assertValue | id=input-vaadin-text-field-26 | (882) 813-1374
		{
			String value = driver.findElement(By.id("input-vaadin-text-field-26")).getAttribute("value");
			assertThat(value, is("(882) 813-1374"));
		}
		// 8 | click | id=input-vaadin-text-field-26 |
		driver.findElement(By.id("input-vaadin-text-field-26")).click();
		// 9 | click | css=vaadin-split-layout |
		driver.findElement(By.cssSelector("vaadin-split-layout")).click();
		// 10 | type | id=input-vaadin-text-field-26 | (882) 813-1567
		driver.findElement(By.id("input-vaadin-text-field-26")).sendKeys("(882) 813-1567");
		// 11 | click | css=vaadin-button:nth-child(2) |
		driver.findElement(By.cssSelector("vaadin-button:nth-child(2)")).click();
		// 12 | click | css=vaadin-grid-cell-content:nth-child(76) |
		elements.get(75).click();
		// 13 | click | css=vaadin-split-layout |
		driver.findElement(By.cssSelector("vaadin-split-layout")).click();
		// 14 | assertValue | id=input-vaadin-text-field-26 | (882) 813-1374
		{
			String value = driver.findElement(By.id("input-vaadin-text-field-26")).getAttribute("value");
			assertThat(value, is("(882) 813-1374"));
		}
	}
}
