package org.ual.hmis.LosMilagritos;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ModificarUsuarioRegistradoCasoIncorrectoTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;
	@Before
	public void setUp() { 
		int browser= 0; 
		Boolean headless = false;

		switch (browser) {
		case 0: 
			System.setProperty("webdriver.gecko.driver",  "drivers/geckodriver.exe");
			FirefoxOptions firefoxOptions = new FirefoxOptions();
//			if (headless) firefoxOptions.addArguments("--headless"); // .setHeadless(headless);
			firefoxOptions.setHeadless(true); 
			driver = new FirefoxDriver(firefoxOptions);
			break;

		case 1: 
			System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
			ChromeOptions chromeOptions = new ChromeOptions();
//			if (headless) chromeOptions.addArguments("--headless"); // .setHeadless(headless);
			chromeOptions.setHeadless(true);
			driver = new ChromeDriver(chromeOptions);
			break;

		default:
			fail("Please select a browser");
			break;
		}

		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}
	@After
	public void tearDown() {
		driver.quit();
	}
	@Test
	public void modificarUsuarioRegistradoCasoIncorrecto() {
		// Test name: Modificar Usuario Registrado Caso Incorrecto
		// Step # | name | target | value
		// 1 | open | https://my-app-1717583869591.azurewebsites.net/ | 
		driver.get("https://my-app-1717583869591.azurewebsites.net/");
		// 2 | Wait for vaadin-grid to be clickable
		WebDriverWait wait = new WebDriverWait(driver, 10);

		//Entrar como usuario a la app
		WebElement usernameField = wait.until(ExpectedConditions.presenceOfElementLocated(By.id("input-vaadin-text-field-6")));
		usernameField.sendKeys("user");

		WebElement passwordField = wait.until(ExpectedConditions.presenceOfElementLocated(By.id("input-vaadin-password-field-7")));
		passwordField.sendKeys("user");

		WebElement loginButton = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("vaadin-button:nth-child(2)")));
		loginButton.click();

		wait.until(ExpectedConditions.elementToBeClickable(By.tagName("vaadin-grid")));
		// 3 | click | css=vaadin-grid-cell-content:nth-child(41) | 
		driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(41)")).click();
		// 4 | assertText | css=vaadin-grid-cell-content:nth-child(41) | Barry
		assertThat(driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(41)")).getText(), is("Barry"));
		// 5 | click | id=input-vaadin-text-field-23 | 
		driver.findElement(By.id("input-vaadin-text-field-23")).click();
		// 6 | sendKeys | id=input-vaadin-text-field-23 | Juan
		wait.until(ExpectedConditions.elementToBeClickable(By.id("input-vaadin-text-field-23"))).sendKeys("Juan");
		// 7 | click | css=vaadin-button:nth-child(1) | 
		driver.findElement(By.cssSelector("vaadin-button:nth-child(1)")).click();
		// 8 | Wait for vaadin-grid-cell-content:nth-child(41) to be clickable
		wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("vaadin-grid-cell-content:nth-child(41)")));
		// 9 | click | css=vaadin-grid-cell-content:nth-child(41) | 
		driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(41)")).click();
		// 10 | assertNotText | css=vaadin-grid-cell-content:nth-child(41) | Juan
		assertThat(driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(41)")).getText(), is(not("Juan")));
		// 11 | click | css=vaadin-button:nth-child(1) | 
		driver.findElement(By.cssSelector("vaadin-button:nth-child(1)")).click();
		// 12 | sendKeys | css=vaadin-grid-cell-content:nth-child(41) | Barry
		driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(41)")).sendKeys("Barry");
		// 13 | assertText | css=vaadin-grid-cell-content:nth-child(41) | Barry
		assertThat(driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(41)")).getText(), is("Barry"));
	}
}
